import type { WorkspaceState } from "./types";

export const workspaceFixture: WorkspaceState = {
  projectName: "霁虹之后",
  selectedSceneId: "scene-02",
  selectedCutId: "cut-06",
  scenes: [
    {
      id: "scene-01",
      number: 1,
      title: "雨夜车站",
      range: "00:00–00:42",
      cutCount: 3,
      status: "succeeded",
    },
    {
      id: "scene-02",
      number: 2,
      title: "霁虹街区",
      range: "00:42–01:18",
      cutCount: 4,
      status: "partial",
    },
    {
      id: "scene-03",
      number: 3,
      title: "清晨天台",
      range: "01:18–02:00",
      cutCount: 3,
      status: "queued",
    },
  ],
  cuts: [
    {
      id: "cut-04",
      sceneId: "scene-02",
      number: 4,
      range: "00:42–00:52",
      duration: "10s",
      purpose: "雨后的街道，霁虹灯倒映在湿漉的地面，车辆驶过。",
      prompt: "雨夜霁虹街道，低机位跟随车辆，水面反光，电影质感，4K。",
      shotSize: "全景",
      cameraMotion: "缓慢推进",
      status: "succeeded",
      assetVersion: "v3",
      visualTone: "rain",
    },
    {
      id: "cut-05",
      sceneId: "scene-02",
      number: 5,
      range: "00:52–00:58",
      duration: "6s",
      purpose: "人群穿梭，霁虹招牌闪烁，城市的节奏加快。",
      prompt: "穿梭夜市人流，霁虹光影，快速剪影，浅景深。",
      shotSize: "中景",
      cameraMotion: "横向跟随",
      status: "running",
      progress: 62,
      visualTone: "neon",
    },
    {
      id: "cut-06",
      sceneId: "scene-02",
      number: 6,
      range: "00:58–01:07",
      duration: "9s",
      purpose: "仰拍高楼大屏幕，广告切换，光影冲击。",
      prompt: "夜晚城市，高楼大厦，大屏幕广告切换。仰拍视角，霁虹光影，电影质感，动态镜头，强烈对比，4K。",
      shotSize: "远景",
      cameraMotion: "缓慢上升",
      status: "failed_retryable",
      error: "服务暂时不可用，未消耗成功镜头",
      visualTone: "error",
    },
    {
      id: "cut-07",
      sceneId: "scene-02",
      number: 7,
      range: "01:07–01:18",
      duration: "11s",
      purpose: "街角咖啡店的橱窗，暖光与霁虹交织。",
      prompt: "夜市街角咖啡店，透过雨水玻璃拍摄，暖冷光交织。",
      shotSize: "中远景",
      cameraMotion: "固定镜头",
      status: "queued",
      visualTone: "pending",
    },
  ],
  preview: {
    status: "ready",
    timelineVersion: "timeline-v7",
  },
  projectStats: {
    succeeded: 4,
    total: 7,
  },
};
