import type { DemoProject, MediaVariants } from "./types";

function poster(scene: number): MediaVariants {
  const id = String(scene).padStart(2, "0");
  const basePath = `/demo/after-rain/posters/scene-${id}`;

  return {
    width400: `${basePath}-400.webp`,
    width800: `${basePath}-800.webp`,
    width1200: `${basePath}-1200.webp`,
  };
}

function previewVideo(scene: number) {
  const id = String(scene).padStart(2, "0");
  return `/demo/after-rain/media/scene-${id}-preview.mp4`;
}

export const demoProject: DemoProject = {
  id: "after-rain",
  title: "After Rain",
  globalStyle: "同一位短发女性、深灰长风衣、雨后城市、紫蓝色电影镜头语言",
  modelTiers: [
    {
      id: "economy",
      label: "经济",
      description: "快速生成，适合草稿探索",
      resolution: "720p",
      videoCoverage: "30%–40%",
      consistency: "基础",
      estimatedDuration: "约 4–6 分钟",
    },
    {
      id: "balanced",
      label: "平衡",
      description: "速度与画质兼顾",
      resolution: "720p",
      videoCoverage: "约 60%",
      consistency: "中高",
      estimatedDuration: "约 8–12 分钟",
    },
    {
      id: "quality",
      label: "质量",
      description: "更高画质，适合最终镜头",
      resolution: "1080p",
      videoCoverage: "80%–100%",
      consistency: "高",
      estimatedDuration: "约 16–24 分钟",
    },
  ],
  selectedModelTierId: "balanced",
  preview: { status: "stale" },
  timelineAnalysis: {
    rulerTicks: [
      { id: "tick-00", label: "00:00", timeSec: 0 },
      { id: "tick-15", label: "00:15", timeSec: 15 },
      { id: "tick-30", label: "00:30", timeSec: 30 },
      { id: "tick-45", label: "00:45", timeSec: 45 },
      { id: "tick-66", label: "01:06", timeSec: 66 },
    ],
    waveformSamples: [
      { timeSec: 0.75, amplitude: 8 },
      { timeSec: 2.25, amplitude: 21 },
      { timeSec: 3.75, amplitude: 34 },
      { timeSec: 5.25, amplitude: 17 },
      { timeSec: 6.75, amplitude: 30 },
      { timeSec: 8.25, amplitude: 13 },
      { timeSec: 9.75, amplitude: 26 },
      { timeSec: 11.25, amplitude: 9 },
      { timeSec: 12.75, amplitude: 22 },
      { timeSec: 14.25, amplitude: 35 },
      { timeSec: 15.75, amplitude: 18 },
      { timeSec: 17.25, amplitude: 31 },
      { timeSec: 18.75, amplitude: 14 },
      { timeSec: 20.25, amplitude: 27 },
      { timeSec: 21.75, amplitude: 10 },
      { timeSec: 23.25, amplitude: 23 },
      { timeSec: 24.75, amplitude: 36 },
      { timeSec: 26.25, amplitude: 19 },
      { timeSec: 27.75, amplitude: 32 },
      { timeSec: 29.25, amplitude: 15 },
      { timeSec: 30.75, amplitude: 28 },
      { timeSec: 32.25, amplitude: 11 },
      { timeSec: 33.75, amplitude: 24 },
      { timeSec: 35.25, amplitude: 37 },
      { timeSec: 36.75, amplitude: 20 },
      { timeSec: 38.25, amplitude: 33 },
      { timeSec: 39.75, amplitude: 16 },
      { timeSec: 41.25, amplitude: 29 },
      { timeSec: 42.75, amplitude: 12 },
      { timeSec: 44.25, amplitude: 25 },
      { timeSec: 45.75, amplitude: 8 },
      { timeSec: 47.25, amplitude: 21 },
      { timeSec: 48.75, amplitude: 34 },
      { timeSec: 50.25, amplitude: 17 },
      { timeSec: 51.75, amplitude: 30 },
      { timeSec: 53.25, amplitude: 13 },
      { timeSec: 54.75, amplitude: 26 },
      { timeSec: 56.25, amplitude: 9 },
      { timeSec: 57.75, amplitude: 22 },
      { timeSec: 59.25, amplitude: 35 },
      { timeSec: 60.75, amplitude: 18 },
      { timeSec: 62.25, amplitude: 31 },
      { timeSec: 63.75, amplitude: 14 },
      { timeSec: 65.25, amplitude: 27 },
    ],
    beats: [
      { id: "beat-08", timeSec: 8 },
      { id: "beat-16", timeSec: 16 },
      { id: "beat-24", timeSec: 24 },
      { id: "beat-31", timeSec: 31 },
      { id: "beat-39", timeSec: 39 },
      { id: "beat-48", timeSec: 48 },
      { id: "beat-56", timeSec: 56 },
    ],
    sections: [
      { id: "section-verse", label: "主歌", startSec: 0, endSec: 24 },
      { id: "section-bridge", label: "过渡", startSec: 24, endSec: 48 },
      { id: "section-chorus", label: "副歌", startSec: 48, endSec: 66 },
    ],
    lyrics: [
      { id: "lyric-platform", text: "离开站台", timeSec: 9 },
      { id: "lyric-reflection", text: "玻璃倒影", timeSec: 28 },
      { id: "lyric-bridge", text: "天桥停留", timeSec: 52 },
    ],
  },
  shots: [
    {
      id: "shot-01",
      number: 1,
      title: "雨夜站台",
      range: "00:00–00:08",
      durationSec: 8,
      description: "她在雨后的高架站台停下，远处列车灯光穿过夜色。",
      prompt: "雨后高架站台，短发女性穿深灰长风衣，紫蓝霓虹反射，电影感。",
      cameraMotion: "缓慢推进",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "available",
      status: "succeeded",
      overridesGlobalStyle: false,
      activeTakeId: "shot-01-take-01",
      takes: [{
        id: "shot-01-take-01",
        label: "Take 01",
        poster: poster(1),
        previewVideo: previewVideo(1),
        generationSnapshot: {
          prompt: "雨后高架站台，短发女性穿深灰长风衣，紫蓝霓虹反射，电影感。",
          cameraMotion: "缓慢推进",
          advanced: { seed: "2468", resolution: "720p" },
          modelTierId: "balanced",
        },
        selected: true,
      }],
      poster: poster(1),
      previewVideo: previewVideo(1),
    },
    {
      id: "shot-02",
      number: 2,
      title: "离开站台",
      range: "00:08–00:16",
      durationSec: 8,
      description: "她走出车站，雨水在街面留下冷色倒影。",
      prompt: "雨后城市车站出口，短发女性走入紫蓝霓虹街道，电影感。",
      cameraMotion: "横向跟随",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "processing",
      status: "queued",
      overridesGlobalStyle: false,
      takes: [],
      poster: poster(2),
      previewVideo: previewVideo(2),
    },
    {
      id: "shot-03",
      number: 3,
      title: "穿过路口",
      range: "00:16–00:24",
      durationSec: 8,
      description: "她穿过安静路口，湿漉的沥青映出城市光色。",
      prompt: "雨后夜晚路口，短发女性中景行走，低机位，紫蓝倒影。",
      cameraMotion: "低机位跟随",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "processing",
      status: "running",
      progress: 54,
      overridesGlobalStyle: false,
      takes: [],
      poster: poster(3),
      previewVideo: previewVideo(3),
    },
    {
      id: "shot-04",
      number: 4,
      title: "玻璃候车亭",
      range: "00:24–00:31",
      durationSec: 7,
      description: "她在玻璃候车亭下停住，霓虹从侧面掠过。",
      prompt: "雨后玻璃候车亭，短发女性侧身，紫蓝霓虹，电影静帧。",
      cameraMotion: "固定镜头",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "available",
      status: "succeeded",
      overridesGlobalStyle: false,
      activeTakeId: "shot-04-take-01",
      takes: [{
        id: "shot-04-take-01",
        label: "Take 01",
        poster: poster(4),
        previewVideo: previewVideo(4),
        generationSnapshot: {
          prompt: "雨后玻璃候车亭，短发女性侧身，紫蓝霓虹，电影静帧。",
          cameraMotion: "固定镜头",
          advanced: { seed: "2468", resolution: "720p" },
          modelTierId: "balanced",
        },
        selected: true,
      }],
      poster: poster(4),
      previewVideo: previewVideo(4),
    },
    {
      id: "shot-05",
      number: 5,
      title: "咖啡窗前",
      range: "00:31–00:39",
      durationSec: 8,
      description: "她站在雨珠密布的咖啡窗前，暖光与冷色街景交织。",
      prompt: "雨后咖啡窗外，短发女性看向暖光室内，紫蓝夜街，电影感。",
      cameraMotion: "缓慢横移",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "failed",
      status: "failed_retryable",
      error: "服务暂时不可用，可重新生成。",
      overridesGlobalStyle: false,
      takes: [],
      poster: poster(5),
      previewVideo: previewVideo(5),
    },
    {
      id: "shot-06",
      number: 6,
      title: "高架桥下",
      range: "00:39–00:48",
      durationSec: 9,
      description: "她沿着高架桥下的湿街独自前行。",
      prompt: "雨后高架桥下，短发女性深灰长风衣，三分之四背影，紫蓝城市夜色。",
      cameraMotion: "后方跟随",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "missing",
      status: "draft",
      overridesGlobalStyle: false,
      takes: [],
      poster: poster(6),
      previewVideo: previewVideo(6),
    },
    {
      id: "shot-07",
      number: 7,
      title: "天桥停留",
      range: "00:48–00:56",
      durationSec: 8,
      description: "她在行人天桥的栏杆前停留，俯瞰雨后车流。",
      prompt: "雨后行人天桥，短发女性靠近栏杆，紫蓝车流光影，电影感。",
      cameraMotion: "缓慢拉远",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "processing",
      status: "queued",
      overridesGlobalStyle: true,
      takes: [],
      poster: poster(7),
      previewVideo: previewVideo(7),
    },
    {
      id: "shot-08",
      number: 8,
      title: "黎明屋顶",
      range: "00:56–01:06",
      durationSec: 10,
      description: "她站在仍有雨水的屋顶，城市从霓虹夜色进入蓝色黎明。",
      prompt: "雨后黎明屋顶，短发女性深灰长风衣，城市天际线，蓝紫电影感。",
      cameraMotion: "缓慢上升",
      advancedSettings: { seed: "2468", resolution: "720p" },
      artifactStatus: "missing",
      status: "draft",
      overridesGlobalStyle: false,
      takes: [],
      poster: poster(8),
      previewVideo: previewVideo(8),
    },
  ],
};
